"""
src/inpainting/inpaint.py
Removes detected poles from images using LaMa inpainting.

How it works:
    1. Takes original images and their corresponding binary masks
    2. Prepares input folder in the format LaMa expects
    3. Calls LaMa's predict.py script via subprocess using the venv_lama Python
    4. Saves the cleaned images to the output folder

Usage:
    python src/inpainting/inpaint.py \
        --images data/test/images/ \
        --masks results/masks/ \
        --output results/inpainted/ \
        --lama_path "C:/Users/sebas/0. Python/lama"
"""

import os
import sys
import shutil
import argparse
import subprocess
import cv2
import numpy as np
from pathlib import Path


# ── Default path to your local LaMa installation ──────────────────────────────
# Change this to match where YOU cloned LaMa on your machine.
# Your teammates will need to update this too, or pass --lama_path when running.
DEFAULT_LAMA_PATH = r"C:\Users\sebas\0. Python\lama"


def parse_args():
    parser = argparse.ArgumentParser(description="Remove poles using LaMa inpainting")

    # Path to the folder containing the original images
    parser.add_argument("--images", type=str, default="data/test/images/",
                        help="Folder with original input images")

    # Path to the folder containing the binary masks generated by mask_generator.py
    parser.add_argument("--masks", type=str, default="results/masks/",
                        help="Folder with binary mask images (white = inpaint this area)")

    # Where to save the final inpainted images
    parser.add_argument("--output", type=str, default="results/inpainted/",
                        help="Folder where cleaned images will be saved")

    # Path to the LaMa repo on this machine
    parser.add_argument("--lama_path", type=str, default=DEFAULT_LAMA_PATH,
                        help="Absolute path to the cloned LaMa repository")

    # Temporary folder used to prepare inputs in LaMa's expected format
    parser.add_argument("--tmp", type=str, default="results/lama_tmp/",
                        help="Temporary folder for LaMa input preparation")

    return parser.parse_args()


def find_image_for_mask(mask_path: Path, images_dir: Path):
    """
    Given a mask filename like '90_png_mask.png', find the corresponding
    original image like '90.png' or '90.jpg' in the images folder.
    LaMa expects image and mask to share the same base name.
    """
    # Remove the '_mask' suffix that mask_generator.py added
    stem = mask_path.stem  # e.g. '90_png_rf_abc123_mask'
    # Strip '_mask' from the end
    if stem.endswith("_mask"):
        stem = stem[:-5]  # remove last 5 chars ('_mask')

    # Try common image extensions
    for ext in [".jpg", ".jpeg", ".png"]:
        candidate = images_dir / (stem + ext)
        if candidate.exists():
            return candidate

    return None


def prepare_lama_input(images_dir: Path, masks_dir: Path, tmp_dir: Path):
    """
    LaMa expects input images and masks to be in the same folder,
    with masks named exactly: <imagename>_mask.png

    This function copies and renames files into that structure.
    """
    tmp_dir.mkdir(parents=True, exist_ok=True)

    paired = []  # list of (image_path, mask_path) pairs that matched

    for mask_path in sorted(masks_dir.glob("*_mask.png")):
        img_path = find_image_for_mask(mask_path, images_dir)

        if img_path is None:
            print(f"  [!] No matching image found for mask: {mask_path.name} — skipping")
            continue

        # Copy image to tmp folder
        dst_img = tmp_dir / img_path.name
        shutil.copy(img_path, dst_img)

        # Copy mask to tmp folder, renamed to match LaMa's convention:
        # image: photo.png → mask: photo_mask.png
        mask_dst_name = img_path.stem + "_mask.png"
        dst_mask = tmp_dir / mask_dst_name
        shutil.copy(mask_path, dst_mask)

        paired.append((img_path, mask_path))
        print(f"  Paired: {img_path.name} ↔ {mask_path.name}")

    return paired


def run_lama(lama_path: Path, tmp_dir: Path, output_dir: Path):
    """
    Calls LaMa's predict.py script as a subprocess using the venv_lama Python.
    LaMa reads from tmp_dir and writes results to output_dir.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # Path to the Python executable inside LaMa's virtual environment
    lama_python = lama_path / "venv_lama" / "Scripts" / "python.exe"

    # Path to LaMa's prediction script
    lama_predict = lama_path / "bin" / "predict.py"

    # Path to LaMa's big-lama model config
    lama_config = lama_path / "big-lama" / "config.yaml"

    # Path to the pretrained checkpoint
    lama_checkpoint = lama_path / "big-lama" / "models" / "best.ckpt"

    # Verify all required files exist before calling subprocess
    for path, label in [
        (lama_python, "LaMa Python venv"),
        (lama_predict, "LaMa predict.py"),
        (lama_checkpoint, "LaMa best.ckpt"),
    ]:
        if not path.exists():
            print(f"[ERROR] {label} not found at: {path}")
            print("        Check your --lama_path and that the venv and weights are set up.")
            sys.exit(1)

    print(f"\nRunning LaMa inpainting...")
    print(f"  Input:      {tmp_dir}")
    print(f"  Output:     {output_dir}")
    print(f"  Checkpoint: {lama_checkpoint}")

    # Build the command that calls LaMa's predict script
    tmp_dir_abs = str(tmp_dir.resolve())
    output_dir_abs = str(output_dir.resolve())
    model_path_abs = str((lama_path / 'big-lama').resolve())

    cmd = [
        str(lama_python),
        str(lama_predict),
        f"model.path={model_path_abs}",
        f"indir={tmp_dir_abs}",
        f"outdir={output_dir_abs}",
        "dataset.img_suffix=.jpg",
    ]
    # Add lama's root to PYTHONPATH so it can find saicinpainting
    env = os.environ.copy()
    env["PYTHONPATH"] = str(lama_path)

    result = subprocess.run(cmd, capture_output=False, text=True, env=env)

    if result.returncode != 0:
        print("\n[ERROR] LaMa exited with an error.")
    else:
        print("\n[OK] LaMa inpainting complete.")


def cleanup(tmp_dir: Path):
    """Remove the temporary input folder after inpainting is done."""
    if tmp_dir.exists():
        shutil.rmtree(tmp_dir)
        print(f"Cleaned up temporary folder: {tmp_dir}")


def main():
    args = parse_args()

    images_dir  = Path(args.images)
    masks_dir   = Path(args.masks)
    output_dir  = Path(args.output)
    lama_path   = Path(args.lama_path)
    tmp_dir     = Path(args.tmp)

    print("=" * 60)
    print("STEP 1: Preparing LaMa input folder")
    print("=" * 60)
    paired = prepare_lama_input(images_dir, masks_dir, tmp_dir)

    if not paired:
        print("\n[ERROR] No image-mask pairs found. Check your --images and --masks paths.")
        sys.exit(1)

    print(f"\n  Found {len(paired)} image-mask pairs.")

    print("\n" + "=" * 60)
    print("STEP 2: Running LaMa inpainting")
    print("=" * 60)
    run_lama(lama_path, tmp_dir, output_dir)

    # print("\n" + "=" * 60)
    # print("STEP 3: Cleanup")
    # print("=" * 60)
    # cleanup(tmp_dir)

    print(f"\n✅ Done! Inpainted images saved to: {output_dir}")


if __name__ == "__main__":
    main()